FROM node:18 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

FROM node:18-alpine AS production

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY app.js .

EXPOSE 3000
CMD ["node", "app.js"]
