# Base image -think of this as your OS + runtime
FROM python:3.12-slim

# Set working directory inside the container
WORKDIR /app

# Copy your code into the container
COPY app.py .

# Command to run when container starts
CMD ["python", "app.py"]
